# Generated by Django 5.0.2 on 2025-11-30 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_alumnos_maestros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosAcademicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_objetivo', models.TextField()),
                ('programa_educativo', models.CharField(blank=True, choices=[('ICC', 'Ingeniería en Ciencias de la Computación'), ('LCC', 'Licenciatura en Ciencias de la Computación'), ('ITI', 'Ingeniería en Tecnologías de la Información')], max_length=50, null=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_realizacion', '-hora_inicio'],
            },
        ),
    ]
